[toolchain]
anchor_version = "0.32.1"
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
vestige = "4RQMkiv5Lp4p862UeQxQs6YgWRPBud2fwLMR5GcSo1bf"

[programs.devnet]
vestige = "4RQMkiv5Lp4p862UeQxQs6YgWRPBud2fwLMR5GcSo1bf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

# MagicBlock Ephemeral Rollup endpoints
[clusters.devnet]
rpc = "https://api.devnet.solana.com"

[clusters.magicblock]
rpc = "https://devnet.magicblock.app"
router = "https://devnet-router.magicblock.app"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
