[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
vestige = "2RuBcnnCXuY7VXxCKXShXw2T5rsGc8xnV6yvdsMwjCoF"

[programs.devnet]
vestige = "2RuBcnnCXuY7VXxCKXShXw2T5rsGc8xnV6yvdsMwjCoF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

# MagicBlock Ephemeral Rollup endpoints
[clusters.devnet]
rpc = "https://api.devnet.solana.com"

[clusters.magicblock]
rpc = "https://devnet.magicblock.app"
router = "https://devnet-router.magicblock.app"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
